<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMasterPage.Master" AutoEventWireup="true" CodeBehind="addcategory.aspx.cs" Inherits="MobileShopping.addcategory" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <center>
        <table width="40%">
            <tr>
                <td align="center" colspan="2">
                    <asp:Label ID="Label1" runat="server" Text="ADD CATEGORY"
                        Font-Bold="True" Font-Italic="True"></asp:Label>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="Label2" runat="server" Text="NAME"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtCategoryName" runat="server" Width="250px"></asp:TextBox><br />
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server"
                        ErrorMessage="Enter  Name Of Category" ForeColor="Red"
                        ValidationGroup="txtbox"
                        ControlToValidate="txtCategoryName"></asp:RequiredFieldValidator>
                </td>
            </tr>
            <tr>
                <td align="center" colspan="2">
                    <asp:Button ID="Button1" runat="server"
                        Text="ADD" OnClick="Button1_Click" ValidationGroup="txtbox" />
                </td>
            </tr>
            <tr>
                <td align="center" colspan="2">
                    <asp:Label ID="lblerror" runat="server" Font-Bold="True" Font-Italic="True"
                        ForeColor="Red"></asp:Label></td>
            </tr>
            <tr>
                <td align="center" colspan="2">
                    <asp:GridView ID="GridView1" runat="server"
                        AutoGenerateColumns="false"
                        AutoGenerateDeleteButton="true"
                        AutoGenerateEditButton="true"
                        DataSourceID="sqlDataSource1"
                        Width="60%"
                        DataKeyNames="cid">
                        <Columns>
                            <asp:BoundField DataField="cid"
                                HeaderText="Catergory Id"
                                InsertVisible="false"
                                ReadOnly="true"
                                SortExpression="cid" />
                            <asp:BoundField DataField="cname"
                                HeaderText="Catergory Name"
                                SortExpression="cid" />
                        </Columns>
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server"
                        ConnectionString="<%$ connectionStrings:con %>"
                        SelectCommand="select * from category"
                        UpdateCommand="update category set cname=@cname where cid=@cid"
                        DeleteCommand="delete from category where cid=@cid"></asp:SqlDataSource>
                </td>
            </tr>
        </table>
    </center>
</asp:Content>
